[package]
name = "Todo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "./main.rs"


[dependencies]
actix-web = "4"
actix-files = "0.5"
diesel = { version = "1.4", features = ["sqlite"] }
dotenv = "0.15"