[package]
name = "Todo"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "main"
path = "./main.rs"


[dependencies]
actix-web = "4.5.1"
actix-files = "0.6.5"
diesel = { version = "2.1.5", features = ["sqlite"] }
dotenv = "0.15"
serde = { version = "1.0.197", features = ["derive"] }