[package]
name = "Todo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "./main.rs"


[dependencies]
actix-web = "4.4.1"
actix-files = "0.6.2"
diesel = { version = "2.1.4", features = ["sqlite"] }
dotenv = "0.15"
serde = { version = "1.0.193", features = ["derive"] }